feat: add label-on-comment workflow to repo
openedx/public-engineering pull request #87
Opened 2022-06-21 15:16 UTC by Carlos-Muniz

Closes https://github.com/openedx/tcril-engineering/issues/322

This will grant the arbi-bom team the ability to edit labels of Github issues, much like how the BTR WG does in the BTR WG repo.

2022-06-21 22:05 UTC, sarina requested changes

2022-06-22 19:20 UTC, Carlos-Muniz commented on .github/workflows/label-on-comment.yml
> +  remove_label:
Why should it say update_labels, rather than add_label?

2022-06-22 19:21 UTC, Carlos-Muniz commented on .github/workflows/label-on-comment.yml
> +  remove_label:
I updated the workflow to address all your other comments so far: 
- Included instructions
- identical to workflow template in .github repo
- only has the one job

2022-06-23 20:30 UTC, sarina approved these changes

2022-06-23 20:44 UTC, merged